## Phase 9 demo: declarative state binding + typed broker events.
## - left: a form whose fields auto-store into plain state fields
##   (bindValue), with the port routed through a validating RequestBroker
##   provider (bindRequest) — digits only, try typing letters
## - right: the LIVE state fields, redrawn every frame straight from the
##   view object, plus a log fed by uiEvents-generated typed events
## ESC quits.

import std/strutils
import chronos
import illview
import illview/dsl/pragmas
import illview/dsl/mount
import illview/dsl/uievents

type
  FormState = ref object
    ## The MODEL: plain data the view binds to; nothing in here knows a widget.
    nameVal: string
    portVal: string
    acceptVal: bool

  BindForm {.view, vbox, spacing: 1.} = ref object of Group
    l1 {.child, caption: "name (bindValue):".}: Label
    name {.child, bindValue: "model.nameVal".}: Input
    l2 {.child, caption: "port (bindRequest, digits only):".}: Label
    port {.child, bindValue: "model.portVal", bindRequest: "SetPortReq".}: Input
    accept {.child, caption: "accept terms", bindValue: "model.acceptVal".}: Checkbox
    run {.child, caption: "Run", emits: "RunRequested".}: Button
    model: FormState # bindValue stores land here (deviation #30)

uiEvents(BindForm)

type
  StatePane = ref object of View
    model: FormState

method draw(sp: StatePane, dc: DrawContext) =
  let st = sp.styleOf(tkText)
  dc.write(0, 0, "live model fields:", sp.styleOf(tkGroupBox))
  dc.write(0, 2, "nameVal   = \"" & sp.model.nameVal & "\"", st)
  dc.write(0, 3, "portVal   = \"" & sp.model.portVal & "\"", st)
  dc.write(0, 4, "acceptVal = " & $sp.model.acceptVal, st)

proc main() {.async.} =
  # replace the generated identity provider: digits only, decoupled from
  # the widget (this is the RequestBroker benefit)
  discard SetPortReq.replaceProvider(DefaultBrokerContext,
    proc(value: string): Result[string, string] =
      if value.len == 0 or value.allCharsInSet({'0'..'9'}):
        ok(value)
      else:
        err("not a number"))

  let app = newApp()
  let win = newWindow("bindings", rect(0, 0, 0, 0))
  win.dock = dkFill
  let cols = newHBox(spacing = 2)
  cols.dock = dkFill

  let model = FormState()
  let form = mount(BindForm)
  form.model = model
  form.hint = (prefHint(30, stretch = 1), prefHint(0, stretch = 1))

  let right = newVBox(spacing = 1)
  right.hint = (prefHint(0, stretch = 1), prefHint(0, stretch = 1))
  let sp = StatePane(model: model)
  initView(sp)
  sp.hint = (prefHint(0, stretch = 1), fixedHint(5))
  let log = newTextView(maxLines = 100)
  log.hint = (prefHint(0, stretch = 1), prefHint(0, stretch = 1))
  right.add sp
  right.add log

  cols.add form
  cols.add right
  win.add cols
  app.desktop.add win

  # typed event -> log (payload generated by uiEvents). emits: fires on the
  # app's session ctx (shared by all views), so we listen on app.sessionCtx.
  # That is the thread's global broker ctx unless one was installed/passed
  # (deviation #27); form.sessionCtx is the same value.
  discard RunRequested.listen(app.sessionCtx,
    proc(ev: RunRequested): Future[void] {.async: (raises: []), gcsafe.} =
      log.addLine "RunRequested(senderId: " & $ev.senderId & ") model: name=" &
        model.nameVal & " port=" & model.portVal & " accept=" & $model.acceptVal)

  log.addLine "type into the form; watch the model pane update"

  app.onInput = proc(ev: InputEvent) {.gcsafe, raises: [].} =
    if ev.kind == ikKey and ev.key == Key.Escape:
      app.stop()

  await app.run()

waitFor main()
