## Custom pragmas for the declarative layer (Phase 5, plan §1).
## `bindTo` is named so because `bind` is a reserved word.
##
## Type-level: view, title(s), hbox, vbox, grid(cols), spacing(n), dock(d)
## Field-level: child, caption(s), dock(d), stretch(n), action(c), bindTo(m)

import ../core/[geometry, bus, theme, view]

template view*() {.pragma.}
  ## Marks a type as a mountable illview screen/component.

template child*() {.pragma.}
  ## Marks a field as a child widget: mount() constructs it and adds it to
  ## the enclosing view (or its layout container).

template title*(s: string) {.pragma.}
  ## Window title (type-level).

template caption*(s: string) {.pragma.}
  ## Initial caption/text of the widget (button/checkbox/label/input/window).

template dock*(d: Dock) {.pragma.}
  ## Dock anchor for the field (or the mounted view itself at type level).

template stretch*(n: int) {.pragma.}
  ## Stretch weight (applied to both axes of the field's size hint).

template alignSelf*(a: Align) {.pragma.}
  ## Cross-axis (box) / in-cell (grid, form) placement of the child:
  ## alStretch (default), alStart, alCenter, alEnd (plan-4 D14). Named
  ## `alignSelf` (not `align`) to avoid Nim's built-in {.align.} pragma.

template anchors*(edges: untyped) {.pragma.}
  ## Edge-anchor a dkNone child to the given parent edges (plan-4 D14):
  ## both edges of an axis => stretch, one => slide, none => stay put.
  ## `edges` is a `set[Anchor]` literal, e.g. {aLeft, aRight}.

template padding*(n: int) {.pragma.}
  ## Content inset in cells; composes with the border (plan-4 D14).

template hbox*() {.pragma.}
  ## Lay the children out in a horizontal box (type-level).

template vbox*() {.pragma.}
  ## Lay the children out in a vertical box (type-level).

template grid*(cols: int) {.pragma.}
  ## Lay the children out in a grid with `cols` columns (type-level).

template form*() {.pragma.}
  ## Lay the children out as a two-column form — (label, control) pairs;
  ## column 0 auto-sizes to the widest label, column 1 stretches (type-level).

template spacing*(n: int) {.pragma.}
  ## Spacing for the hbox/vbox/grid/form container (type-level).

template action*(c: Command) {.pragma.}
  ## Broker command: the widget auto-publishes UiAction(c, id) on activation.

template bindTo*(m: string) {.pragma.}
  ## Wires the field's PRIMARY closure slot to the named proc on the
  ## enclosing view: proc m(self: EnclosingType, sender: FieldType).
  ## Primary slots: Button.onClick, Checkbox.onToggle, Radio.onSelect,
  ## ListView.onActivate, Input.onSubmit, Editor.onChange.

# --- state binding & typed events (iteration 2, plan-2 D4/D5) -----------------

template bindValue*(field: string) {.pragma.}
  ## Widget -> field: the named field on the enclosing view is kept current
  ## on every value change (Input/Editor: text, Checkbox: checked,
  ## Radio/ListView/Table: selected). uiEvents(T) additionally generates the
  ## inverse writer `set<Field>(self, v)` (plan-3 D10): store + Set-signal
  ## to the widget on its instance ctx, bypassing any bindRequest provider.

template bindRequest*(name: string) {.pragma.}
  ## Route the value update through a sync RequestBroker generated by
  ## uiEvents(T): `name.request(value)`; combined with bindValue the field
  ## stores whatever the (replaceable) provider returns — external
  ## validation/normalization with the widget fully decoupled.

template emits*(name: string) {.pragma.}
  ## On activation, emit the broker event `name` generated by uiEvents(T)
  ## (payload: senderId + the widget's value snapshot).

# --- instance-ctx listeners (iteration 3, plan-3 D9) ---------------------------

template on*(spec: untyped) {.pragma.}
  ## Ctx-scoped listener installation: `on: {EventType: "handlerName", ...}`.
  ## mount() installs each handler as a listener on THIS field's widget
  ## brokerCtx — the same event type on two widgets never cross-talks.
  ## Handler arities: proc(self: T) or proc(self: T, ev: EventType).
  ## EventType is a vocab event (Clicked, TextChanged, ...) or any
  ## EventBroker type (incl. uiEvents-generated ones). Teardown is recorded
  ## on the widget's disposers (drop-then-release, plan-3 D11/D12).

# --- styling (iteration 2, plan-2 D3) ----------------------------------------

template border*(k: BorderKind) {.pragma.}
  ## Border drawn by the parent; content area shrinks by 1 cell per side.

template boxTitle*(s: string) {.pragma.}
  ## Title on the top border (requires a border).

template shadow*() {.pragma.}
  ## TV-style shadow (recolors the cells right/below of the view).

template fg*(c: ForegroundColor) {.pragma.}
  ## Foreground override merged over the theme token.

template bg*(c: BackgroundColor) {.pragma.}
  ## Background override merged over the theme token.

template focusFg*(c: ForegroundColor) {.pragma.}
  ## Foreground while the view is focused.

template focusBg*(c: BackgroundColor) {.pragma.}
  ## Background while the view is focused.
